service: rtc
frameworkVersion: '3'
custom:
  githubOrg: ${file(./private.${opt:stage, 'dev'}.json):githubOrg}
  repositoryName: ${file(./private.${opt:stage, 'dev'}.json):repositoryName}
  bucketName: ${file(./private.${opt:stage, 'dev'}.json):bucketName}
  siteName: ${file(./private.${opt:stage, 'dev'}.json):siteName}
provider:
  name: aws
resources:
  Parameters:
    OIDCProviderArn:
      Description: Arn for the GitHub OIDC Provider.
      Default: ""
      Type: String
  Conditions:
    CreateOIDCProvider: !Equals 
      - !Ref OIDCProviderArn
      - ""
  Resources:
    RtcGithubRunner:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "RtcGithubRunner"
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Action: sts:AssumeRoleWithWebIdentity
              Principal:
                Federated: !If 
                  - CreateOIDCProvider
                  - !Ref GithubOidc
                  - !Ref OIDCProviderArn
              Condition:
                StringLike:
                  token.actions.githubusercontent.com:sub: 
                    - Fn::Join:
                      - ':'
                      -
                        - 'repo'
                        - ${file(./private.${opt:stage, 'dev'}.json):githubOrg}/${file(./private.${opt:stage, 'dev'}.json):repositoryName}
                        - '*'
        Policies:
          - PolicyName: RtcGithubPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "s3:PutObject"
                    - "s3:GetObject"
                    - "s3:ListBucket"
                  Resource:
                    - Fn::Join:
                      - ':'
                      -
                        - 'arn:aws:s3::'
                        - ${file(./private.${opt:stage, 'dev'}.json):bucketName}/apps/${file(./private.${opt:stage, 'dev'}.json):siteName}/test/*     
    GithubOidc:
      Type: AWS::IAM::OIDCProvider
      Condition: CreateOIDCProvider
      Properties:
        Url: https://token.actions.githubusercontent.com
        ClientIdList: 
          - sts.amazonaws.com
        ThumbprintList:
          - 6938fd4d98bab03faadb97b34396831e3780aea1