name: Build
on:
  push:
    branches:
      - dev
      - master
permissions:
  id-token: write
  contents: read
jobs:
  build-deploy:
    uses: rollthecloudinc/druid/.github/workflows/druid.yml@master
    secrets: inherit