name: Build
on:
  push:
    branches:
      - dev
      - master
permissions:
  id-token: write
  contents: read
jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: '16.x'
          registry-url: "https://npm.pkg.github.com"
      - run: npm install
        name: Install packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RTC_GITHUB_REGISTRY }}
      - run: npm run prerender:${{ secrets.ENVIRONMENT_NAME }}
      - run: echo "::set-output name=stamp::$(date +'%Y%m%d%H%M%S')"
        name: Generate Release Stamp
        id: release
      - name: Push to build repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'dist/spear'
          destination-github-username: 'rollthecloudinc'
          destination-repository-name: 'rtc-build'
          target-branch: master