name: Deploy
on:
  push:
    branches:
      - dev
      - master
permissions:
  id-token: write
  contents: read
jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        name: Prerender
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
      - run: echo "::set-output name=stamp::$(date +'%Y%m%d%H%M%S')"
        name: Generate Release Stamp
        id: release
      - run: |
          d=$(aws cloudfront get-distribution-config --id E4AYXOHKH4E34)
          echo "::set-output name=distribution::$d"
        name: Get Distribution
        id: cloudfront
      - run: | 
          echo "::set-output name=originPath::$(echo "${{ steps.cloudfront.outputs.distribution }}" | jq '.DistributionConfig.Origins.Items[0].OriginPath')"
        name: Extract Origin Path
        id: extraction
      - run: echo ${{ steps.extraction.outputs.originPath }}
      - run: |
          d=$(echo ${{ steps.cloudfront.outputs.distribution }})
          p=$(echo ${{ steps.extraction.outputs.originPath }})
          update=$(echo $d | sed "s%$p%/apps/${{ secrets.APP_NAME }}/${{ steps.release.outputs.stamp }}%gi")
          echo "::set-output name=distribution::$($update | jq '.DistributionConfig')"
        name: Replace origin path
        id: replace
      - run: echo ${{ steps.replace.outputs.distribution }}