name: Build
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: "https://npm.pkg.github.com"
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RTC_GITHUB_REGISTRY }}
      - run: npm install -g angular-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RTC_GITHUB_REGISTRY }}
  prerender:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: ng run ipe:prerender:production --no-guess-routes --routes-file ./data/routes.txt