name: Build
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  setip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: "https://npm.pkg.github.com"
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RTC_GITHUB_REGISTRY }}
      - run: npm run prerender:dev
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::989992233821:role/RtcGithubRunner
          aws-region: us-east-1
      - run: echo "::set-output name=stamp::$(date +'%Y%m%d%H%M%S')"
        id: release
      - run: aws s3 sync ./dist/spear s3://classifieds-ui-dev/apps/rollthecloud.com/${{ steps.release.outputs.stamp }}