name: Deploy
on:
  push:
    branches:
      - dev
permissions:
  id-token: write
  contents: read
jobs:
  build:
    uses: rollthecloudinc/druid/.github/workflows/druid-workflow.yml@master
    with:
      ENVIRONMENT: dev